"""Turning block summaries into function names.

Naming is deterministic: a name is built from the block's category and the
identifiers it produces, never generated by a model. Nothing in this module
makes a network call.
"""

from __future__ import annotations
import keyword
import re
from typing import Protocol
from .categories import verb_for
from .models import BlockSummary

MAX_NAME_LENGTH = 40

_IDENTIFIER_SAFE = re.compile(r"[^0-9a-zA-Z_]+")
_CAMEL_BOUNDARY = re.compile(r"(?<=[a-z0-9])(?=[A-Z])")


def sanitise(raw: str) -> str:
    """Coerce a candidate string into a valid snake_case identifier.

    Strips decoration (backticks, a leading `def `, a trailing `()`) and splits
    camelCase, then enforces the identifier rules. Returns `""` if nothing
    usable survives, which tells the caller to fall back rather than emit a
    broken name — a subject taken from source can be any of these shapes.
    """
    text = raw.strip()
    if not text:
        return ""
    if text.startswith("```"):
        lines = [ln for ln in text.splitlines() if not ln.strip().startswith("```")]
        text = "\n".join(lines).strip()
    text = text.splitlines()[0].strip() if text.splitlines() else ""
    text = text.strip("`'\" \t")

    if text.startswith("def "):
        text = text[4:]
    text = text.split("(")[0].strip()

    text = _CAMEL_BOUNDARY.sub("_", text)
    text = _IDENTIFIER_SAFE.sub("_", text).strip("_").lower()
    text = re.sub(r"__+", "_", text)

    if not text:
        return ""
    if text[0].isdigit():
        text = f"step_{text}"
    if keyword.iskeyword(text) or keyword.issoftkeyword(text):
        text = f"{text}_step"
    if len(text) > MAX_NAME_LENGTH:
        text = text[:MAX_NAME_LENGTH].rstrip("_")
    return text if text.isidentifier() else ""


class FunctionNamer(Protocol):
    """Anything that can name a block from its summary.

    The extension point for callers that want their own naming scheme. It stays
    a protocol rather than a concrete class so a custom namer can be injected
    without this package growing a dependency to support it.
    """

    def name_for(self, summary: BlockSummary, category: str = "") -> str:
        """Return a snake_case name, or `""` to defer to the fallback."""
        ...


class DeterministicNamer:
    """Names blocks from the summary alone. The only namer, and the default.

    Builds `<verb>_<subject>` from the block's category and the first
    identifier it produces. The names are plain (`load_sales_df` rather than
    `ingest_regional_sales`) but they are stable across runs, cost nothing, and
    are always valid identifiers.
    """

    def __init__(self, category_lookup: dict[int, str] | None = None) -> None:
        self._categories = category_lookup or {}

    def name_for(self, summary: BlockSummary, category: str = "") -> str:
        """Build `<verb>_<subject>` from the summary."""
        verb = verb_for(category) if category else "process"
        subject = ""
        for candidate in (*summary.outputs, *summary.modifies, *summary.inputs):
            if not candidate.startswith("_"):
                subject = candidate
                break

        if not subject and summary.operations:
            subject = summary.operations[0]

        name = f"{verb}_{subject}" if subject else verb
        return sanitise(name) or "process_data"


def deduplicate(names: list[str]) -> list[str]:
    """Make every name unique by suffixing repeats.

    Two blocks can legitimately summarise identically — two cleaning passes over
    different frames — and will therefore be named the same. Later definitions
    would silently shadow earlier ones, so repeats become `clean_df_2`,
    `clean_df_3`, and so on.
    """
    seen: dict[str, int] = {}
    result: list[str] = []
    for name in names:
        if name not in seen:
            seen[name] = 1
            result.append(name)
            continue
        seen[name] += 1
        candidate = f"{name}_{seen[name]}"
        while candidate in seen:
            seen[name] += 1
            candidate = f"{name}_{seen[name]}"
        seen[candidate] = 1
        result.append(candidate)
    return result
